/**
 * Project/Area short abbreviations (docs/dev/technical-design-project-area-
 * abbreviations.md) - a short, user-editable, case-insensitive-unique tag
 * (e.g. "AT", "AoT") every Project/Area can carry, stored in its own
 * frontmatter (`abbrev:`, see domain/markdown.ts's parseFrontMatter/
 * writeFrontMatterIntoContent). Two independent jobs live here: generating a
 * rough default from an item's name, and validating a candidate (typed by
 * the user, or generated by this same module) against the two things that
 * can make one invalid - another item's abbrev, or a reserved flow-state
 * word.
 *
 * Pure, zero RN/SDK imports - same domain/ convention as flowState.ts,
 * unit-testable via the project's standalone Node scripts without a device.
 */
import {isContextTag} from './flowState';
import {extractContextTags} from './markdown';
import {ItemStatus} from './types';

/** Just what validateAbbrev/generateDefaultAbbrev need from every OTHER item currently carrying an abbrev - callers build this from CachedItem[], excluding the item being edited (so re-saving its own current value never flags itself as a duplicate). */
export interface ExistingAbbrev {
  value: string;
  itemName: string;
}

/** Case-insensitive comparison only - the value actually stored/displayed always keeps whatever casing the user (or the generator) wrote; nothing here force-cases it. */
function normalize(value: string): string {
  return value.trim().toLowerCase();
}

export type AbbrevInvalidReason =
  | {kind: 'empty'}
  | {kind: 'reserved'}
  | {kind: 'duplicate'; usedBy: string};

export interface AbbrevValidation {
  valid: boolean;
  /** Set only when `valid` is false - the ONE thing wrong, for the UI's single inline error line. Deliberately one reason, never a list; reserved-word wins over duplicate-checking (in practice the two are mutually exclusive: a reserved word can never become another item's saved abbrev). */
  reason?: AbbrevInvalidReason;
}

/**
 * Whether `candidate` is safe to save as an abbreviation. Two rules:
 * - Must not collide (case-insensitive) with a reserved flow-state word -
 *   reuses domain/flowState.ts's `isContextTag` exclusion list as-is
 *   (next/someday/maybe/now/wf(/*)/waiting-for(:*)/due(:*)) rather than maintaining
 *   a second reserved-word list that could drift from it.
 * - Must not collide (case-insensitive) with any other Project/Area's
 *   abbreviation - global scope across both kinds together, not scoped
 *   per-kind (an Area and a Project can't share one either).
 */
export function validateAbbrev(candidate: string, existingAbbrevs: ExistingAbbrev[]): AbbrevValidation {
  const trimmed = candidate.trim();
  if (trimmed.length === 0) return {valid: false, reason: {kind: 'empty'}};
  const normalized = normalize(trimmed);
  if (!isContextTag(normalized)) return {valid: false, reason: {kind: 'reserved'}};
  const collision = existingAbbrevs.find(entry => normalize(entry.value) === normalized);
  if (collision) return {valid: false, reason: {kind: 'duplicate', usedBy: collision.itemName}};
  return {valid: true};
}

function splitWords(name: string): string[] {
  return name.trim().split(/\s+/).filter(Boolean);
}

/**
 * A rough default abbreviation from `name` (it does not have to be perfect;
 * it is always user-editable after generation):
 * - 3+ words: initials of the first three words, uppercased.
 * - exactly 2 words: initials of both words (2 chars), uppercased.
 * - 1 word: the first three letters of that word, uppercased (shorter than
 *   3 letters if the word itself is).
 *
 * On a collision (with an existing abbreviation, or a reserved word -
 * checked via validateAbbrev, so this can never drift from that rule):
 * first tries appending one more letter, drawn from whatever's left of the
 * last word this heuristic read from (e.g. "Atruvia" -> base "ATR", with
 * "UVIA" available to extend with); if that's exhausted or still collides,
 * falls back to a trailing number (2, 3, ...) until unique. No attempt at
 * elegant capitalization (an "AoT"-style default is a manual edit) and no
 * word-splitting beyond whitespace (punctuation, digits, non-Latin scripts
 * all just flow through as "a word").
 */
export function generateDefaultAbbrev(name: string, existingAbbrevs: ExistingAbbrev[]): string {
  const words = splitWords(name);
  const isFree = (candidate: string) => validateAbbrev(candidate, existingAbbrevs).valid;

  let base: string;
  let extraSource: string;
  if (words.length >= 3) {
    base = words
      .slice(0, 3)
      .map(w => w[0])
      .join('')
      .toUpperCase();
    extraSource = words[2].slice(1);
  } else if (words.length === 2) {
    base = words.map(w => w[0]).join('').toUpperCase();
    extraSource = words[1].slice(1);
  } else if (words.length === 1) {
    base = words[0].slice(0, 3).toUpperCase();
    extraSource = words[0].slice(3);
  } else {
    // No words at all (blank/whitespace-only name) - degenerate input;
    // still resolved to *something* unique below rather than throwing.
    base = 'XX';
    extraSource = '';
  }

  if (isFree(base)) return base;

  let widened = base;
  for (const ch of extraSource) {
    widened = widened + ch.toUpperCase();
    if (isFree(widened)) return widened;
  }

  for (let n = 2; n < 1000; n++) {
    const candidate = `${widened}${n}`;
    if (isFree(candidate)) return candidate;
  }
  // Practically unreachable (1000 straight collisions) - keeps the function
  // total rather than possibly returning something already taken.
  return `${widened}${Date.now()}`;
}

/**
 * Case-insensitive lookup of `tag` against `items`' own `abbrev` field - the
 * Daily context-tag filter's project/area resolution (docs/dev/technical-design-
 * project-area-abbreviations.md's "Daily filter" decision: a tag that names
 * a real Project/Area pulls in that whole item's tasks/meetings, independent
 * of whether the literal tag text is present on them). Returns the matching
 * item's `path`, or null if `tag` doesn't currently name any Project/Area.
 * Generic over just the two fields this needs (not importing CachedItem
 * here - domain/ stays free of storage/ imports) so storage/dailyAggregate.ts
 * can pass its own CachedItem[] straight through.
 */
export function resolveAbbrevPath<T extends {abbrev: string | null; path: string}>(
  tag: string | null,
  items: T[],
): string | null {
  if (!tag) return null;
  const normalized = normalize(tag);
  const match = items.find(item => item.abbrev !== null && normalize(item.abbrev) === normalized);
  return match ? match.path : null;
}

/** The Project/Area a resolved abbreviation quick-file match points at - just enough to build a Destination/InboxFilingTarget from (docs/dev/history/technical-design-abbrev-quick-file.md). `tag` is the exact matched tag text (lowercased, no leading `#`, as `extractContextTags` returns it) - callers use it with `domain/markdown.ts`'s `removeTagFromText` to strip it from the saved text once it's done its job. */
export interface AbbrevFileMatch {
  kind: 'project' | 'area';
  name: string;
  path: string;
  tag: string;
}

/**
 * The first #tag in `text` (in appearance order) that names a registered,
 * Active or On Hold Project/Area's abbreviation - the target for the
 * ui/QuickAddWidget.tsx "File: <Name>"/"+ Add to <Name>" quick-file
 * affordance. Reuses
 * extractContextTags for tag scanning (already lowercased, deduped,
 * reserved flow-state/due/#now words excluded - an abbreviation can never
 * collide with those per validateAbbrev, so nothing here needs to re-derive
 * that exclusion).
 *
 * `excludePath` is the item's own current location (fixedDestination.path
 * when it's an 'item' destination, null for Inbox) - a tag that resolves to
 * wherever the item already is/would be created is a no-op, so this returns
 * null rather than a self-target. This check happens on the FIRST matching
 * tag only: if that tag is a self-match, quick-file is unavailable even if a
 * later tag in the text would resolve elsewhere - the first recognized tag
 * decides, which keeps the rule simple.
 *
 * Deliberately broader than domain/destination.ts's own destinationCandidates
 * (the picker Daily/Capture use for a brand-new item with no tag typed),
 * which is Active-only - On Hold is excluded there specifically to avoid
 * overloading a browsed list. That reasoning doesn't apply here (this is a
 * typed-tag match, never a list), so On Hold items ARE valid quick-file
 * targets - an explicit, confirmed divergence, not an oversight. Done/
 * Archived never match either way.
 */
export function resolveAbbrevFileTarget<
  T extends {abbrev: string | null; path: string; name: string; kind: 'project' | 'area'; status: ItemStatus},
>(text: string, items: T[], excludePath: string | null): AbbrevFileMatch | null {
  for (const tag of extractContextTags(text)) {
    const match = items.find(
      item =>
        item.abbrev !== null &&
        item.abbrev.toLowerCase() === tag &&
        (item.status === 'active' || item.status === 'on-hold'),
    );
    if (match) return match.path === excludePath ? null : {kind: match.kind, name: match.name, path: match.path, tag};
  }
  return null;
}
