// Bundles the user guide (docs/user/*.md) for the in-app help.
// Design: docs/dev/technical-design-in-app-help.md §3.1. Pure: no file access here.

/** First `# ` heading of a page, or the fallback. */
export function pageTitle(markdown, fallback) {
  const m = /^#\s+(.+?)\s*$/m.exec(markdown);
  return m ? m[1] : fallback;
}

/**
 * Groups from index.md: each `## Heading` starts a group, each list item
 * linking to `page.md` adds that page (first link of the item). Pages not in
 * `pageIds` are skipped.
 */
export function parseIndexGroups(indexMarkdown, pageIds) {
  const known = new Set(pageIds);
  const groups = [];
  let current = null;
  for (const line of indexMarkdown.replace(/\r\n/g, '\n').split('\n')) {
    const h = /^##\s+(.+?)\s*$/.exec(line);
    if (h) {
      current = {title: h[1], pageIds: []};
      groups.push(current);
      continue;
    }
    const item = /^\s*[-*]\s+.*?\[[^\]]+\]\(([^)#\s]+)\.md(?:#[^)]*)?\)/.exec(line);
    if (item && current && known.has(item[1]) && !current.pageIds.includes(item[1])) {
      current.pageIds.push(item[1]);
    }
  }
  return groups.filter(g => g.pageIds.length > 0);
}

/**
 * `files`: [{id, markdown}] for every docs/user page (id = file name without .md).
 * Returns {groups, pages}: groups from index.md, plus a group "More" for pages
 * index.md doesn't list; pages keyed by id with their title.
 */
export function buildUserDocs(files) {
  const byId = new Map(files.map(f => [f.id, f.markdown]));
  const pageIds = files.map(f => f.id).filter(id => id !== 'index').sort();
  const groups = byId.has('index') ? parseIndexGroups(byId.get('index'), pageIds) : [];
  const listed = new Set(groups.flatMap(g => g.pageIds));
  const unlisted = pageIds.filter(id => !listed.has(id));
  if (unlisted.length > 0) groups.push({title: 'More', pageIds: unlisted});
  const pages = {};
  for (const f of [...files].sort((a, b) => a.id.localeCompare(b.id))) {
    pages[f.id] = {title: f.id === 'index' ? 'Overview' : pageTitle(f.markdown, f.id), markdown: f.markdown.replace(/\r\n/g, '\n')};
  }
  return {groups, pages};
}

export function renderUserDocsTs(docs) {
  return [
    '// GENERATED by scripts/gen-bundled-content.mjs from docs/user/*.md - do not edit, not committed.',
    '/* eslint-disable */',
    'export interface UserDocsGroup {',
    '  title: string;',
    '  pageIds: string[];',
    '}',
    'export interface UserDocsPage {',
    '  title: string;',
    '  markdown: string;',
    '}',
    '',
    '/** Groups in the order of docs/user/index.md; `pages.index` is the overview. */',
    `export const USER_DOCS: {groups: UserDocsGroup[]; pages: Record<string, UserDocsPage>} = ${JSON.stringify(docs, null, 2)};`,
    '',
  ].join('\n');
}
